# Copyright (c) 2021 Cisco Systems, Inc. and its affiliates
# All rights reserved.
# Use of this source code is governed by a BSD 3-Clause License
# that can be found in the LICENSE file.

get:
  tags:
    - StreamManagement
  summary: Transmitter Configuration Request (with path)
  description: "Return Transmitter Configuration information (with support for specifying an issuer)."
  parameters:
    - $ref: "../openapi.yaml#/components/parameters/issuer"
  responses:
    '200':
      description: |
        A set of Claims about the Transmitter's configuration,
        including all necessary endpoints and public key location information.
      content:
        application/json:
          schema:
             $ref: "../openapi.yaml#/components/schemas/TransmitterConfiguration"
