# Copyright (c) 2021 Cisco Systems, Inc. and its affiliates
# All rights reserved.
# Use of this source code is governed by a
# BSD 3-Clause License that can be found in the LICENSE file.

# ref: https://docs.travis-ci.com/user/languages/python
language: python
python:
  - "3.8"
  - "3.9"
# command to install dependencies
install: "pip install -r requirements.txt"
# command to run tests
script: nosetests
