services:
  transmitter:
    build:
      context: ./transmitter
      dockerfile: Dockerfile
    ports:
      - "443:443"
    volumes:
      - ./transmitter:/usr/src/app
    environment:
      - FLASK_ENV=development
