# Copyright (c) 2021 Cisco Systems, Inc. and its affiliates
# All rights reserved.
# Use of this source code is governed by a BSD 3-Clause License
# that can be found in the LICENSE file.

services:
  transmitter:
    build:
      context: ./transmitter
      dockerfile: Dockerfile
    ports:
      - "443:443"
    volumes:
      - ./transmitter:/usr/src/app
      - keys-volume:/usr/keys
    environment:
      - FLASK_ENV=development
      # Path to our JWKS file
      - JWKS_PATH=/usr/keys/jwks.json
      # The key ID of the JSON Web Key Set that is currently in use
      # update this if we want to rotate keys
      - JWK_KEY_ID=transmitter-ES256-001

  receiver:
    depends_on:
      - transmitter
    build:
      context: ./receiver
      dockerfile: Dockerfile
    ports:
      - "5003:5003"
    volumes:
      - ./receiver:/usr/src/app
      - keys-volume:/usr/keys
    environment:
      # Path to our JWKS file
      - JWKS_PATH=/usr/keys/jwks.json
      # The key ID of the JSON Web Key Set that is currently in use
      # update this if we want to rotate keys
      - JWK_KEY_ID=transmitter-ES256-001
      # Allow TLS without verifying cert
      - UNSAFE_TLS=True

volumes:
  # we will store our JWKS file here so that it is persistent between builds
  keys-volume:
