# Copyright (c) 2021 Cisco Systems, Inc. and its affiliates
# All rights reserved.
# Licensed under BSD 3-Clause License

services:
  transmitter:
    build:
      context: ./transmitter
      dockerfile: Dockerfile
    ports:
      - "443:443"
    volumes:
      - ./transmitter:/usr/src/app
    environment:
      - FLASK_ENV=development
